// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/gshireesh/terraform-provider-shireesh/components"
	"github.com/gshireesh/terraform-provider-shireesh/internal/component"
	"github.com/gshireesh/terraform-provider-shireesh/internal/generator"
)

// isEnvChar returns true if the byte is an ASCII letter, digit, or underscore.
func isEnvChar(ch byte) bool {
	return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '_'
}

func main() {
	var (
		providerName    string
		outDir          string
		includeHTTP     bool
		serviceName     string
		protoPackage    string
		goPackagePrefix string
		protoOut        string // new: where to place proto + generated pb files (root api directory)
		// auth override flags
		authEnable     bool
		authPackage    string
		authGoPackage  string
		authTitle      string
		authVersion    string
		authHost       string
		authTokenURL   string
		authReadScope  string
		authWriteScope string
	)
	flag.StringVar(&providerName, "provider-name", "shireesh", "provider name to use in combined proto")
	flag.StringVar(&outDir, "out", "internal/provider/generated", "output directory for generated files (non-proto)")
	flag.BoolVar(&includeHTTP, "http", true, "include grpc-gateway HTTP annotations in proto")
	flag.StringVar(&serviceName, "service-name", "GrpcTerraformService", "service name to use in combined proto")
	flag.StringVar(&protoPackage, "proto-package", "component", "protobuf package name (used when auth disabled)")
	flag.StringVar(&goPackagePrefix, "go-package-prefix", "github.com/gshireesh/terraform-provider-shireesh/internal/provider/generated", "go package prefix for option go_package (when auth disabled)")
	flag.StringVar(&protoOut, "proto-out", "api/shireesh.com/config/v1", "output directory for protobuf schema + generated pb code (root-level for external import)")
	flag.BoolVar(&authEnable, "auth", true, "enable carbon style auth swagger header override")
	flag.StringVar(&authPackage, "auth-package", "shireesh.com.api.config.v1", "auth proto package")
	// Updated default to module path so external repos can import github.com/gshireesh/terraform-provider-shireesh/api
	flag.StringVar(&authGoPackage, "auth-go-package", "github.com/gshireesh/terraform-provider-shireesh/api", "auth go_package override (module import path for generated pb)")
	flag.StringVar(&authTitle, "auth-title", "Carbon API", "auth swagger title")
	flag.StringVar(&authVersion, "auth-version", "1.0.0", "auth swagger version")
	flag.StringVar(&authHost, "auth-host", "carbon.shireesh.com", "auth swagger host")
	flag.StringVar(&authTokenURL, "auth-token-url", "https://auth.shireesh.com/v1/oauth/token", "oauth2 token url")
	flag.StringVar(&authReadScope, "auth-read-scope", "read", "oauth2 read scope")
	flag.StringVar(&authWriteScope, "auth-write-scope", "write", "oauth2 write scope")
	flag.Parse()

	// Typed specs only
	specs := []component.Spec{
		components.SimpleSpec(),
		//components.ComplexSpec(),
		//components.ModesSpec(),
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatalf("create out dir: %v", err)
	}

	var authCfg *generator.AuthConfig
	if authEnable {
		authCfg = &generator.AuthConfig{Title: authTitle, Version: authVersion, Host: authHost, TokenURL: authTokenURL, ReadScope: authReadScope, WriteScope: authWriteScope, Package: authPackage, GoPackage: authGoPackage}
	}

	if err := generator.GenerateAllWithAuthProto(specs, outDir, filepath.Join("components", ".tags"), includeHTTP, serviceName, protoPackage, goPackagePrefix, protoOut, authCfg); err != nil {
		log.Fatalf("generate: %v", err)
	}

	// Write provider name constant for use in provider.Metadata plus env prefix/constants.
	provFile := filepath.Join(outDir, "provider_name.gen.go")
	// Sanitize providerName for env prefix: uppercase and replace non-alnum with underscore.
	sanitized := providerName
	for i := 0; i < len(sanitized); i++ {
		ch := sanitized[i]
		if !isEnvChar(ch) { // replace invalid character with underscore
			b := []byte(sanitized)
			b[i] = '_'
			sanitized = string(b)
		}
	}
	envPrefix := strings.ToUpper(sanitized)
	content := fmt.Sprintf("// Code generated by componentgen; DO NOT EDIT.\npackage generated\n\nconst ProviderName = \"%s\"\nconst ProviderEnvPrefix = \"%s\"\n\n// Standard environment variable names derived from ProviderEnvPrefix.\nconst (\n\tEnvAPIBaseURL = ProviderEnvPrefix + \"_API_BASE_URL\"\n\tEnvOAuth2TokenURL = ProviderEnvPrefix + \"_OAUTH2_TOKEN_URL\"\n\tEnvClientID = ProviderEnvPrefix + \"_CLIENT_ID\"\n\tEnvClientSecret = ProviderEnvPrefix + \"_CLIENT_SECRET\"\n\tEnvScopes = ProviderEnvPrefix + \"_SCOPES\"\n)\n", providerName, envPrefix)
	if err := os.WriteFile(provFile, []byte(content), 0o644); err != nil {
		log.Fatalf("write provider_name: %v", err)
	}

	fmt.Printf("generated %d components into %s (proto_out=%s http=%v service=%s proto_pkg=%s go_pkg_prefix=%s provider=%s)\n", len(specs), outDir, protoOut, includeHTTP, serviceName, protoPackage, goPackagePrefix, providerName)
}
