// Code generated by componentgen; DO NOT EDIT.
package fakeserver

import (
	"context"
	"fmt"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	api "github.com/gshireesh/terraform-provider-shireesh/api/shireesh.com/config/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/reflection"
	"net"
	"net/http"
	"net/http/httptest"
	"sync"
	"time"
)

// InMemoryServer implements api.GrpcTerraformServiceServer with in-memory storage.
type InMemoryServer struct {
	api.UnimplementedGrpcTerraformServiceServer
	mu          sync.RWMutex
	simpleStore map[string]*api.SimpleReadOutput
}

func NewInMemoryServer() *InMemoryServer {
	s := &InMemoryServer{}
	s.simpleStore = make(map[string]*api.SimpleReadOutput)
	return s
}

func (s *InMemoryServer) SimpleCreate(ctx context.Context, req *api.SimpleCreateRequest) (*api.SimpleCreateResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	id := fmt.Sprintf("id-%d", time.Now().UnixNano())
	out := &api.SimpleCreateOutput{Id: id}
	if req != nil && req.Item != nil {
		out.Value = req.Item.Value
		out.Flags = req.Item.Flags
		out.Counts = req.Item.Counts
		out.Score = req.Item.Score
	}
	if s.simpleStore == nil {
		s.simpleStore = make(map[string]*api.SimpleReadOutput)
	}
	s.simpleStore[id] = &api.SimpleReadOutput{
		Id:     out.Id,
		Value:  out.Value,
		Flags:  out.Flags,
		Counts: out.Counts,
		Score:  out.Score,
	}
	return &api.SimpleCreateResponse{Item: out}, nil
}

func (s *InMemoryServer) SimpleRead(ctx context.Context, req *api.SimpleReadRequest) (*api.SimpleReadResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if req == nil || req.Id == "" {
		return &api.SimpleReadResponse{}, nil
	}
	if it, ok := s.simpleStore[req.Id]; ok {
		return &api.SimpleReadResponse{Item: &api.SimpleReadOutput{
			Id:     it.Id,
			Value:  it.Value,
			Flags:  it.Flags,
			Counts: it.Counts,
			Score:  it.Score,
		}}, nil
	}
	return &api.SimpleReadResponse{}, nil
}

func (s *InMemoryServer) SimpleUpdate(ctx context.Context, req *api.SimpleUpdateRequest) (*api.SimpleUpdateResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	it, ok := s.simpleStore[req.GetId()]
	if !ok {
		return &api.SimpleUpdateResponse{}, nil
	}
	if req != nil && req.Item != nil {
		it.Value = req.Item.Value
		it.Flags = req.Item.Flags
		it.Counts = req.Item.Counts
		it.Score = req.Item.Score
	}
	out := &api.SimpleUpdateOutput{
		Id:     it.Id,
		Value:  it.Value,
		Flags:  it.Flags,
		Counts: it.Counts,
		Score:  it.Score,
	}
	return &api.SimpleUpdateResponse{Item: out}, nil
}

func (s *InMemoryServer) SimpleDelete(ctx context.Context, req *api.SimpleDeleteRequest) (*api.SimpleDeleteResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.simpleStore != nil {
		delete(s.simpleStore, req.GetId())
	}
	return &api.SimpleDeleteResponse{Success: true}, nil
}

// Start launches a gRPC server and HTTP JSON gateway on a local ephemeral address.
// Returns the *httptest.Server (for HTTP base URL) and a grpc Dial target (host:port).
func (s *InMemoryServer) Start(ctx context.Context) (*httptest.Server, string, error) {
	// gRPC on random port
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return nil, "", err
	}
	grpcSrv := grpc.NewServer(grpc.Creds(insecure.NewCredentials()))
	api.RegisterGrpcTerraformServiceServer(grpcSrv, s)
	reflection.Register(grpcSrv)
	go grpcSrv.Serve(lis)
	grpcTarget := lis.Addr().String()
	// HTTP JSON gateway mux that proxies to the same server
	glue := runtime.NewServeMux()
	cc, err := grpc.DialContext(ctx, grpcTarget, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, "", err
	}
	if err := api.RegisterGrpcTerraformServiceHandlerClient(ctx, glue, api.NewGrpcTerraformServiceClient(cc)); err != nil {
		return nil, "", err
	}
	h := http.NewServeMux()
	h.Handle("/", glue)
	server := httptest.NewServer(h)
	return server, grpcTarget, nil
}
