// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shireesh.com/api/config/v1/components.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SimpleCreateInput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleCreateInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleCreateInput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleCreateInputMultiError, or nil if none found.
func (m *SimpleCreateInput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleCreateInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleCreateInputMultiError(errors)
	}

	return nil
}

// SimpleCreateInputMultiError is an error wrapping multiple validation errors
// returned by SimpleCreateInput.ValidateAll() if the designated constraints
// aren't met.
type SimpleCreateInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleCreateInputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleCreateInputMultiError) AllErrors() []error { return m }

// SimpleCreateInputValidationError is the validation error returned by
// SimpleCreateInput.Validate if the designated constraints aren't met.
type SimpleCreateInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleCreateInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleCreateInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleCreateInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleCreateInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleCreateInputValidationError) ErrorName() string {
	return "SimpleCreateInputValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleCreateInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleCreateInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleCreateInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleCreateInputValidationError{}

// Validate checks the field values on SimpleCreateOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleCreateOutput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleCreateOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleCreateOutputMultiError, or nil if none found.
func (m *SimpleCreateOutput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleCreateOutput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleCreateOutputMultiError(errors)
	}

	return nil
}

// SimpleCreateOutputMultiError is an error wrapping multiple validation errors
// returned by SimpleCreateOutput.ValidateAll() if the designated constraints
// aren't met.
type SimpleCreateOutputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleCreateOutputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleCreateOutputMultiError) AllErrors() []error { return m }

// SimpleCreateOutputValidationError is the validation error returned by
// SimpleCreateOutput.Validate if the designated constraints aren't met.
type SimpleCreateOutputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleCreateOutputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleCreateOutputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleCreateOutputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleCreateOutputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleCreateOutputValidationError) ErrorName() string {
	return "SimpleCreateOutputValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleCreateOutputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleCreateOutput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleCreateOutputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleCreateOutputValidationError{}

// Validate checks the field values on SimpleReadOutput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleReadOutput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleReadOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleReadOutputMultiError, or nil if none found.
func (m *SimpleReadOutput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleReadOutput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleReadOutputMultiError(errors)
	}

	return nil
}

// SimpleReadOutputMultiError is an error wrapping multiple validation errors
// returned by SimpleReadOutput.ValidateAll() if the designated constraints
// aren't met.
type SimpleReadOutputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleReadOutputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleReadOutputMultiError) AllErrors() []error { return m }

// SimpleReadOutputValidationError is the validation error returned by
// SimpleReadOutput.Validate if the designated constraints aren't met.
type SimpleReadOutputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleReadOutputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleReadOutputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleReadOutputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleReadOutputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleReadOutputValidationError) ErrorName() string { return "SimpleReadOutputValidationError" }

// Error satisfies the builtin error interface
func (e SimpleReadOutputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleReadOutput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleReadOutputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleReadOutputValidationError{}

// Validate checks the field values on SimpleUpdateInput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleUpdateInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleUpdateInput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleUpdateInputMultiError, or nil if none found.
func (m *SimpleUpdateInput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleUpdateInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleUpdateInputMultiError(errors)
	}

	return nil
}

// SimpleUpdateInputMultiError is an error wrapping multiple validation errors
// returned by SimpleUpdateInput.ValidateAll() if the designated constraints
// aren't met.
type SimpleUpdateInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleUpdateInputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleUpdateInputMultiError) AllErrors() []error { return m }

// SimpleUpdateInputValidationError is the validation error returned by
// SimpleUpdateInput.Validate if the designated constraints aren't met.
type SimpleUpdateInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleUpdateInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleUpdateInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleUpdateInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleUpdateInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleUpdateInputValidationError) ErrorName() string {
	return "SimpleUpdateInputValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleUpdateInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleUpdateInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleUpdateInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleUpdateInputValidationError{}

// Validate checks the field values on SimpleUpdateOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleUpdateOutput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleUpdateOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleUpdateOutputMultiError, or nil if none found.
func (m *SimpleUpdateOutput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleUpdateOutput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleUpdateOutputMultiError(errors)
	}

	return nil
}

// SimpleUpdateOutputMultiError is an error wrapping multiple validation errors
// returned by SimpleUpdateOutput.ValidateAll() if the designated constraints
// aren't met.
type SimpleUpdateOutputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleUpdateOutputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleUpdateOutputMultiError) AllErrors() []error { return m }

// SimpleUpdateOutputValidationError is the validation error returned by
// SimpleUpdateOutput.Validate if the designated constraints aren't met.
type SimpleUpdateOutputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleUpdateOutputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleUpdateOutputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleUpdateOutputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleUpdateOutputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleUpdateOutputValidationError) ErrorName() string {
	return "SimpleUpdateOutputValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleUpdateOutputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleUpdateOutput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleUpdateOutputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleUpdateOutputValidationError{}

// Validate checks the field values on SimpleOpenInput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleOpenInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleOpenInput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleOpenInputMultiError, or nil if none found.
func (m *SimpleOpenInput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleOpenInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleOpenInputMultiError(errors)
	}

	return nil
}

// SimpleOpenInputMultiError is an error wrapping multiple validation errors
// returned by SimpleOpenInput.ValidateAll() if the designated constraints
// aren't met.
type SimpleOpenInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleOpenInputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleOpenInputMultiError) AllErrors() []error { return m }

// SimpleOpenInputValidationError is the validation error returned by
// SimpleOpenInput.Validate if the designated constraints aren't met.
type SimpleOpenInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleOpenInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleOpenInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleOpenInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleOpenInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleOpenInputValidationError) ErrorName() string { return "SimpleOpenInputValidationError" }

// Error satisfies the builtin error interface
func (e SimpleOpenInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleOpenInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleOpenInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleOpenInputValidationError{}

// Validate checks the field values on SimpleOpenOutput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleOpenOutput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleOpenOutput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleOpenOutputMultiError, or nil if none found.
func (m *SimpleOpenOutput) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleOpenOutput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Value

	// no validation rules for Score

	if len(errors) > 0 {
		return SimpleOpenOutputMultiError(errors)
	}

	return nil
}

// SimpleOpenOutputMultiError is an error wrapping multiple validation errors
// returned by SimpleOpenOutput.ValidateAll() if the designated constraints
// aren't met.
type SimpleOpenOutputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleOpenOutputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleOpenOutputMultiError) AllErrors() []error { return m }

// SimpleOpenOutputValidationError is the validation error returned by
// SimpleOpenOutput.Validate if the designated constraints aren't met.
type SimpleOpenOutputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleOpenOutputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleOpenOutputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleOpenOutputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleOpenOutputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleOpenOutputValidationError) ErrorName() string { return "SimpleOpenOutputValidationError" }

// Error satisfies the builtin error interface
func (e SimpleOpenOutputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleOpenOutput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleOpenOutputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleOpenOutputValidationError{}

// Validate checks the field values on SimpleCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleCreateRequestMultiError, or nil if none found.
func (m *SimpleCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleCreateRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleCreateRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleCreateRequestValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleCreateRequestMultiError(errors)
	}

	return nil
}

// SimpleCreateRequestMultiError is an error wrapping multiple validation
// errors returned by SimpleCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type SimpleCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleCreateRequestMultiError) AllErrors() []error { return m }

// SimpleCreateRequestValidationError is the validation error returned by
// SimpleCreateRequest.Validate if the designated constraints aren't met.
type SimpleCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleCreateRequestValidationError) ErrorName() string {
	return "SimpleCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleCreateRequestValidationError{}

// Validate checks the field values on SimpleCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleCreateResponseMultiError, or nil if none found.
func (m *SimpleCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleCreateResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleCreateResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleCreateResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleCreateResponseMultiError(errors)
	}

	return nil
}

// SimpleCreateResponseMultiError is an error wrapping multiple validation
// errors returned by SimpleCreateResponse.ValidateAll() if the designated
// constraints aren't met.
type SimpleCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleCreateResponseMultiError) AllErrors() []error { return m }

// SimpleCreateResponseValidationError is the validation error returned by
// SimpleCreateResponse.Validate if the designated constraints aren't met.
type SimpleCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleCreateResponseValidationError) ErrorName() string {
	return "SimpleCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleCreateResponseValidationError{}

// Validate checks the field values on SimpleReadRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleReadRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleReadRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleReadRequestMultiError, or nil if none found.
func (m *SimpleReadRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleReadRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SimpleReadRequestMultiError(errors)
	}

	return nil
}

// SimpleReadRequestMultiError is an error wrapping multiple validation errors
// returned by SimpleReadRequest.ValidateAll() if the designated constraints
// aren't met.
type SimpleReadRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleReadRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleReadRequestMultiError) AllErrors() []error { return m }

// SimpleReadRequestValidationError is the validation error returned by
// SimpleReadRequest.Validate if the designated constraints aren't met.
type SimpleReadRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleReadRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleReadRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleReadRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleReadRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleReadRequestValidationError) ErrorName() string {
	return "SimpleReadRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleReadRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleReadRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleReadRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleReadRequestValidationError{}

// Validate checks the field values on SimpleReadResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleReadResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleReadResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleReadResponseMultiError, or nil if none found.
func (m *SimpleReadResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleReadResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleReadResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleReadResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleReadResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleReadResponseMultiError(errors)
	}

	return nil
}

// SimpleReadResponseMultiError is an error wrapping multiple validation errors
// returned by SimpleReadResponse.ValidateAll() if the designated constraints
// aren't met.
type SimpleReadResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleReadResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleReadResponseMultiError) AllErrors() []error { return m }

// SimpleReadResponseValidationError is the validation error returned by
// SimpleReadResponse.Validate if the designated constraints aren't met.
type SimpleReadResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleReadResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleReadResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleReadResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleReadResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleReadResponseValidationError) ErrorName() string {
	return "SimpleReadResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleReadResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleReadResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleReadResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleReadResponseValidationError{}

// Validate checks the field values on SimpleUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleUpdateRequestMultiError, or nil if none found.
func (m *SimpleUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleUpdateRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleUpdateRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleUpdateRequestValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleUpdateRequestMultiError(errors)
	}

	return nil
}

// SimpleUpdateRequestMultiError is an error wrapping multiple validation
// errors returned by SimpleUpdateRequest.ValidateAll() if the designated
// constraints aren't met.
type SimpleUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleUpdateRequestMultiError) AllErrors() []error { return m }

// SimpleUpdateRequestValidationError is the validation error returned by
// SimpleUpdateRequest.Validate if the designated constraints aren't met.
type SimpleUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleUpdateRequestValidationError) ErrorName() string {
	return "SimpleUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleUpdateRequestValidationError{}

// Validate checks the field values on SimpleUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleUpdateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleUpdateResponseMultiError, or nil if none found.
func (m *SimpleUpdateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleUpdateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleUpdateResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleUpdateResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleUpdateResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleUpdateResponseMultiError(errors)
	}

	return nil
}

// SimpleUpdateResponseMultiError is an error wrapping multiple validation
// errors returned by SimpleUpdateResponse.ValidateAll() if the designated
// constraints aren't met.
type SimpleUpdateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleUpdateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleUpdateResponseMultiError) AllErrors() []error { return m }

// SimpleUpdateResponseValidationError is the validation error returned by
// SimpleUpdateResponse.Validate if the designated constraints aren't met.
type SimpleUpdateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleUpdateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleUpdateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleUpdateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleUpdateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleUpdateResponseValidationError) ErrorName() string {
	return "SimpleUpdateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleUpdateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleUpdateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleUpdateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleUpdateResponseValidationError{}

// Validate checks the field values on SimpleDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleDeleteRequestMultiError, or nil if none found.
func (m *SimpleDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SimpleDeleteRequestMultiError(errors)
	}

	return nil
}

// SimpleDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by SimpleDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type SimpleDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleDeleteRequestMultiError) AllErrors() []error { return m }

// SimpleDeleteRequestValidationError is the validation error returned by
// SimpleDeleteRequest.Validate if the designated constraints aren't met.
type SimpleDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleDeleteRequestValidationError) ErrorName() string {
	return "SimpleDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleDeleteRequestValidationError{}

// Validate checks the field values on SimpleDeleteResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleDeleteResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleDeleteResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleDeleteResponseMultiError, or nil if none found.
func (m *SimpleDeleteResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleDeleteResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return SimpleDeleteResponseMultiError(errors)
	}

	return nil
}

// SimpleDeleteResponseMultiError is an error wrapping multiple validation
// errors returned by SimpleDeleteResponse.ValidateAll() if the designated
// constraints aren't met.
type SimpleDeleteResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleDeleteResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleDeleteResponseMultiError) AllErrors() []error { return m }

// SimpleDeleteResponseValidationError is the validation error returned by
// SimpleDeleteResponse.Validate if the designated constraints aren't met.
type SimpleDeleteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleDeleteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleDeleteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleDeleteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleDeleteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleDeleteResponseValidationError) ErrorName() string {
	return "SimpleDeleteResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleDeleteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleDeleteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleDeleteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleDeleteResponseValidationError{}

// Validate checks the field values on SimpleOpenRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SimpleOpenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleOpenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleOpenRequestMultiError, or nil if none found.
func (m *SimpleOpenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleOpenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleOpenRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleOpenRequestValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleOpenRequestValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleOpenRequestMultiError(errors)
	}

	return nil
}

// SimpleOpenRequestMultiError is an error wrapping multiple validation errors
// returned by SimpleOpenRequest.ValidateAll() if the designated constraints
// aren't met.
type SimpleOpenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleOpenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleOpenRequestMultiError) AllErrors() []error { return m }

// SimpleOpenRequestValidationError is the validation error returned by
// SimpleOpenRequest.Validate if the designated constraints aren't met.
type SimpleOpenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleOpenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleOpenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleOpenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleOpenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleOpenRequestValidationError) ErrorName() string {
	return "SimpleOpenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleOpenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleOpenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleOpenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleOpenRequestValidationError{}

// Validate checks the field values on SimpleOpenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SimpleOpenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SimpleOpenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SimpleOpenResponseMultiError, or nil if none found.
func (m *SimpleOpenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SimpleOpenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SimpleOpenResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SimpleOpenResponseValidationError{
					field:  "Item",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SimpleOpenResponseValidationError{
				field:  "Item",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SimpleOpenResponseMultiError(errors)
	}

	return nil
}

// SimpleOpenResponseMultiError is an error wrapping multiple validation errors
// returned by SimpleOpenResponse.ValidateAll() if the designated constraints
// aren't met.
type SimpleOpenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SimpleOpenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SimpleOpenResponseMultiError) AllErrors() []error { return m }

// SimpleOpenResponseValidationError is the validation error returned by
// SimpleOpenResponse.Validate if the designated constraints aren't met.
type SimpleOpenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SimpleOpenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SimpleOpenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SimpleOpenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SimpleOpenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SimpleOpenResponseValidationError) ErrorName() string {
	return "SimpleOpenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SimpleOpenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSimpleOpenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SimpleOpenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SimpleOpenResponseValidationError{}
