// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package generator

import (
	"os"
	"path/filepath"
)

func GenerateDefaults(outDir string) error {
	content := `// Code generated by componentgen; DO NOT EDIT.
package generated

import (
	"net/http"
	"strings"
)

type APIClient struct {
	BaseURL  string
	HTTP    *http.Client
	Insecure bool
	Bearer   string
}

func (c *APIClient) GRPCTarget() string {
	base := c.BaseURL
	if strings.HasPrefix(base, "http://") { base = strings.TrimPrefix(base, "http://") } else if strings.HasPrefix(base, "https://") { base = strings.TrimPrefix(base, "https://") }
	if i := strings.Index(base, "/"); i >= 0 { base = base[:i] }
	return base
}

type Defaults struct { ServiceName, APIBaseURL, Environment string; Insecure bool }

var DefaultConfig = Defaults{ ServiceName: "GrpcTerraformService", APIBaseURL: "http://localhost:8080", Insecure: true, Environment: "dev" }
`
	return os.WriteFile(filepath.Join(outDir, "defaults.gen.go"), []byte(content), 0o644)
}
