// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package generator

import (
	"bytes"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/gshireesh/terraform-provider-shireesh/internal/component"
)

const registryTemplate = `// Code generated by componentgen; DO NOT EDIT.
package generated

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
)

var Components = struct {
	Resources []func() resource.Resource
	DataSources []func() datasource.DataSource
	EphemeralResources []func() ephemeral.EphemeralResource
}{
	Resources: []func() resource.Resource{ {{- range . }} {{ if .HasRole "resource" }} New{{ .Name | Pascal }}Resource, {{ end }} {{- end }} },
	DataSources: []func() datasource.DataSource{ {{- range . }} {{ if .HasRole "datasource" }} New{{ .Name | Pascal }}DataSource, {{ end }} {{- end }} },
	EphemeralResources: []func() ephemeral.EphemeralResource{ {{- range . }} {{ if .HasRole "ephemeral" }} New{{ .Name | Pascal }}Ephemeral, {{ end }} {{- end }} },
}
`

func GenerateRegistry(specs []component.Spec, outDir string) error {
	file := filepath.Join(outDir, "registry.gen.go")
	var buf bytes.Buffer
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	t := template.Must(template.New("registry").Funcs(funcMap()).Parse(registryTemplate))
	if err := t.Execute(&buf, specs); err != nil {
		return err
	}
	return os.WriteFile(file, buf.Bytes(), 0o644)
}
