// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package generator

import (
	"errors"
	"fmt"
	"strings"
	"text/template"

	"github.com/gshireesh/terraform-provider-shireesh/internal/component"
)

// Templates split out to keep files short

const modelTemplate = `// Code generated by componentgen; DO NOT EDIT.
package generated

import "github.com/hashicorp/terraform-plugin-framework/types"

type {{ .Name | Pascal }}Model struct {
{{ range .Fields }}	{{ .Name | Pascal }} {{ ModelFieldType . }} ` + "`tfsdk:\"{{ .Name }}\"`" + `
{{ end }}}
`

const combinedProtoTemplateAuth = `// Code generated by componentgen; DO NOT EDIT.
{{ if .Auth }}syntax = "proto3";
package {{ .Auth.Package }};
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
option go_package = "{{ .Auth.GoPackage }}";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: { title: "{{ .Auth.Title }}"; version: "{{ .Auth.Version }}"; }
  host: "{{ .Auth.Host }}";
  security_definitions: {
    security: { key: "oauth2", value: { type: TYPE_OAUTH2; flow: FLOW_APPLICATION; token_url: "{{ .Auth.TokenURL }}"; scopes: { scope: { key: "{{ .Auth.ReadScope }}"; value: "Read access"; }; scope: { key: "{{ .Auth.WriteScope }}"; value: "write access"; }; } } }
    security: { key: "bearerAuth", value: { type: TYPE_API_KEY; name: "Authorization"; in: IN_HEADER; } }
  }
  security: [ { security_requirement: { key: "oauth2"; value: { scope: ["{{ .Auth.ReadScope }}", "{{ .Auth.WriteScope }}"]; }; }, security_requirement: { key: "bearerAuth"; value: {}; } } ];
};
{{ else }}syntax = "proto3";
package {{ .Package }};
{{ if .HTTPImport }}import "google/api/annotations.proto";{{ end }}
option go_package = "{{ .GoPackage }}";
{{ end }}

// Messages
{{ range .Specs }}
// Component: {{ .Spec.Name }}
{{ range .Messages }}
message {{ .Name }} {
{{ range .Fields }}	{{ if .Repeated }}repeated {{ end }}{{ .Type }} {{ .Name }} = {{ .Tag }}; // {{ .Comment }}
{{ end }}
}
{{ end }}
{{ end }}

// Combined Service
service {{ .Service }} {
{{ range .Specs }}
{{ if .HasResource }}	rpc {{ .Spec.Name | Pascal }}Create({{ .Spec.Name | Pascal }}CreateRequest) returns ({{ .Spec.Name | Pascal }}CreateResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { post: "{{ HttpCreate .Spec.Name }}" body: "item" };
	}{{ else }};{{ end }}
	rpc {{ .Spec.Name | Pascal }}Read({{ .Spec.Name | Pascal }}ReadRequest) returns ({{ .Spec.Name | Pascal }}ReadResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { get: "{{ HttpRead .Spec.Name }}" };
	}{{ else }};{{ end }}
	rpc {{ .Spec.Name | Pascal }}Update({{ .Spec.Name | Pascal }}UpdateRequest) returns ({{ .Spec.Name | Pascal }}UpdateResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { put: "{{ HttpUpdate .Spec.Name }}" body: "item" };
	}{{ else }};{{ end }}
	rpc {{ .Spec.Name | Pascal }}Delete({{ .Spec.Name | Pascal }}DeleteRequest) returns ({{ .Spec.Name | Pascal }}DeleteResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { delete: "{{ HttpDelete .Spec.Name }}" };
	}{{ else }};{{ end }}
{{ end }}
{{ if .HasDataSource }}	rpc {{ .Spec.Name | Pascal }}DataSourceRead({{ .Spec.Name | Pascal }}DataSourceReadRequest) returns ({{ .Spec.Name | Pascal }}DataSourceReadResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { get: "{{ HttpDsRead .Spec.Name }}" };
	}{{ else }};{{ end }}
{{ end }}
{{ if .HasEphemeral }}	rpc {{ .Spec.Name | Pascal }}Open({{ .Spec.Name | Pascal }}OpenRequest) returns ({{ .Spec.Name | Pascal }}OpenResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { post: "{{ HttpOpen .Spec.Name }}" body: "item" };
	}{{ else }};{{ end }}
{{ end }}
{{ end }}
}
`

const goRoleTemplateV2 = `// Code generated by componentgen; DO NOT EDIT.
 package generated
 
 import (
   	"context"
   	{{- if eq .Role "resource" }}
   	// grpc client imports
   	"github.com/hashicorp/terraform-plugin-framework/resource"
   	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
   	{{- if NeedsTypesImport .Spec }}
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/hashicorp/terraform-plugin-framework/attr"
    {{- end }}
   	"google.golang.org/grpc"
   	"google.golang.org/grpc/credentials/insecure"
   	"google.golang.org/grpc/metadata"
   	{{- end }}
   	{{- if eq .Role "datasource" }}
   	"github.com/hashicorp/terraform-plugin-framework/datasource"
   	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
    {{- if NeedsTypesImport .Spec }}
    "github.com/hashicorp/terraform-plugin-framework/types"
    {{- end }}
   	"google.golang.org/grpc"
   	"google.golang.org/grpc/credentials/insecure"
   	"google.golang.org/grpc/metadata"
   	{{- end }}
   	{{- if eq .Role "ephemeral" }}
   	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
   	ephschema "github.com/hashicorp/terraform-plugin-framework/ephemeral/schema"
    {{- if NeedsTypesImport .Spec }}
    "github.com/hashicorp/terraform-plugin-framework/types"
    {{- end }}
   	"google.golang.org/grpc"
   	"google.golang.org/grpc/credentials/insecure"
   	"google.golang.org/grpc/metadata"
   	{{- end }}
   	api "github.com/gshireesh/terraform-provider-shireesh/api/shireesh.com/config/v1"
 )

{{- if eq .Role "resource" }}
func New{{ .Spec.Name | Pascal }}Resource() resource.Resource { return &{{ .Spec.Name | Pascal }}Resource{} }

type {{ .Spec.Name | Pascal }}Resource struct{ client *APIClient }

func (r *{{ .Spec.Name | Pascal }}Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) { resp.TypeName = req.ProviderTypeName + "_{{ .Spec.Name }}" }
func (r *{{ .Spec.Name | Pascal }}Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{}
	{{- range .Spec.Fields }}
	attrs["{{ .Name }}"] = {{ ResourceAttr . }}
	{{- end }}
	resp.Schema = schema.Schema{ Attributes: attrs }
}
func (r *{{ .Spec.Name | Pascal }}Resource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil { return }
	c, ok := req.ProviderData.(*APIClient)
	if ok { r.client = c }
}
func (r *{{ .Spec.Name | Pascal }}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	if r.client == nil { return }
	// Read plan
	var plan {{ .Spec.Name | Pascal }}Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() { return }
	// Build request
	in := &api.{{ .Spec.Name | Pascal }}CreateInput{}
	{{- range .Spec.Fields }}
	{{- if eq .Name "id" }}{{ else }}
	{{- if eq .Type "string" }}
	if !plan.{{ .Name | Pascal }}.IsNull() && !plan.{{ .Name | Pascal }}.IsUnknown() {
		in.{{ .Name | Pascal }} = plan.{{ .Name | Pascal }}.ValueString()
	}
	{{- end }}
	{{- if eq .Type "int64" }}
	if !plan.{{ .Name | Pascal }}.IsNull() && !plan.{{ .Name | Pascal }}.IsUnknown() {
		in.{{ .Name | Pascal }} = plan.{{ .Name | Pascal }}.ValueInt64()
	}
	{{- end }}
	{{- if eq .Type "list" }}
	// list of {{ .ElemType }}
	in.{{ .Name | Pascal }} = tfList{{ if eq .ElemType "bool" }}Bools{{ else if eq .ElemType "number" }}Float64s{{ else }}Strings{{ end }}(ctx, plan.{{ .Name | Pascal }})
	{{- end }}
	{{- end }}
	{{- end }}
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	res, err := cli.{{ .Spec.Name | Pascal }}Create(ctx, &api.{{ .Spec.Name | Pascal }}CreateRequest{Item: in})
	if err != nil { resp.Diagnostics.AddError("create failed", err.Error()); return }
	if res == nil || res.Item == nil { resp.Diagnostics.AddError("create failed", "empty response"); return }
	// Set state
	var state {{ .Spec.Name | Pascal }}Model
	state.Id = types.StringValue(res.Item.Id)
	{{- range .Spec.Fields }}
	{{- if eq .Name "id" }}{{ else if eq .Type "string" }}
	state.{{ .Name | Pascal }} = types.StringValue(res.Item.{{ .Name | Pascal }})
	{{- else if eq .Type "int64" }}
	state.{{ .Name | Pascal }} = types.Int64Value(res.Item.{{ .Name | Pascal }})
	{{- else if eq .Type "list" }}
	if plan.{{ .Name | Pascal }}.IsNull() || plan.{{ .Name | Pascal }}.IsUnknown() {
		if len(res.Item.{{ .Name | Pascal }}) == 0 {
			state.{{ .Name | Pascal }} = types.ListNull({{ if eq .ElemType "bool" }}types.BoolType{{ else if eq .ElemType "number" }}types.Float64Type{{ else }}types.StringType{{ end }})
		} else {
			state.{{ .Name | Pascal }} = list{{ if eq .ElemType "bool" }}Bools{{ else if eq .ElemType "number" }}Float64s{{ else }}Strings{{ end }}ToTF(ctx, res.Item.{{ .Name | Pascal }})
		}
	} else {
		state.{{ .Name | Pascal }} = list{{ if eq .ElemType "bool" }}Bools{{ else if eq .ElemType "number" }}Float64s{{ else }}Strings{{ end }}ToTF(ctx, res.Item.{{ .Name | Pascal }})
	}
	{{- end }}
	{{- end }}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *{{ .Spec.Name | Pascal }}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	if r.client == nil { return }
	var state {{ .Spec.Name | Pascal }}Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() { return }
	if state.Id.IsNull() || state.Id.IsUnknown() { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	res, err := cli.{{ .Spec.Name | Pascal }}Read(ctx, &api.{{ .Spec.Name | Pascal }}ReadRequest{Id: state.Id.ValueString()})
	if err != nil { resp.Diagnostics.AddError("read failed", err.Error()); return }
	if res == nil || res.Item == nil || res.Item.Id == "" { resp.State.RemoveResource(ctx); return }
	state.Id = types.StringValue(res.Item.Id)
	{{- range .Spec.Fields }}
	{{- if eq .Name "id" }}{{ else if eq .Type "string" }}
	state.{{ .Name | Pascal }} = types.StringValue(res.Item.{{ .Name | Pascal }})
	{{- else if eq .Type "int64" }}
	state.{{ .Name | Pascal }} = types.Int64Value(res.Item.{{ .Name | Pascal }})
	{{- else if eq .Type "list" }}
	if len(res.Item.{{ .Name | Pascal }}) == 0 && (state.{{ .Name | Pascal }}.IsNull() || state.{{ .Name | Pascal }}.IsUnknown()) {
		// keep null for absent lists
	} else {
		state.{{ .Name | Pascal }} = list{{ if eq .ElemType "bool" }}Bools{{ else if eq .ElemType "number" }}Float64s{{ else }}Strings{{ end }}ToTF(ctx, res.Item.{{ .Name | Pascal }})
	}
	{{- end }}
	{{- end }}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *{{ .Spec.Name | Pascal }}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	if r.client == nil { return }
	var plan {{ .Spec.Name | Pascal }}Model
	var state {{ .Spec.Name | Pascal }}Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	in := &api.{{ .Spec.Name | Pascal }}UpdateInput{}
	{{- range .Spec.Fields }}
	{{- if eq .Name "id" }}{{ else if eq .Type "string" }}
	if !plan.{{ .Name | Pascal }}.IsNull() && !plan.{{ .Name | Pascal }}.IsUnknown() { in.{{ .Name | Pascal }} = plan.{{ .Name | Pascal }}.ValueString() }
	{{- else if eq .Type "int64" }}
	if !plan.{{ .Name | Pascal }}.IsNull() && !plan.{{ .Name | Pascal }}.IsUnknown() { in.{{ .Name | Pascal }} = plan.{{ .Name | Pascal }}.ValueInt64() }
	{{- else if eq .Type "list" }}
	in.{{ .Name | Pascal }} = tfList{{ if eq .ElemType "bool" }}Bools{{ else if eq .ElemType "number" }}Float64s{{ else }}Strings{{ end }}(ctx, plan.{{ .Name | Pascal }})
	{{- end }}
	{{- end }}
	res, err := cli.{{ .Spec.Name | Pascal }}Update(ctx, &api.{{ .Spec.Name | Pascal }}UpdateRequest{Id: state.Id.ValueString(), Item: in})
	if err != nil { resp.Diagnostics.AddError("update failed", err.Error()); return }
	if res == nil || res.Item == nil { resp.Diagnostics.AddError("update failed", "empty response"); return }
	state.Id = types.StringValue(res.Item.Id)
	{{- range .Spec.Fields }}
	{{- if eq .Name "id" }}{{ else if eq .Type "string" }}
	state.{{ .Name | Pascal }} = types.StringValue(res.Item.{{ .Name | Pascal }})
	{{- else if eq .Type "int64" }}
	state.{{ .Name | Pascal }} = types.Int64Value(res.Item.{{ .Name | Pascal }})
	{{- else if eq .Type "list" }}
	if plan.{{ .Name | Pascal }}.IsNull() || plan.{{ .Name | Pascal }}.IsUnknown() {
		// retain previous state if attribute was not specified in plan
	} else {
		state.{{ .Name | Pascal }} = list{{ if eq .ElemType "bool" }}Bools{{ else if eq .ElemType "number" }}Float64s{{ else }}Strings{{ end }}ToTF(ctx, res.Item.{{ .Name | Pascal }})
	}
	{{- end }}
	{{- end }}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *{{ .Spec.Name | Pascal }}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	if r.client == nil { return }
	var state {{ .Spec.Name | Pascal }}Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Delete(ctx, &api.{{ .Spec.Name | Pascal }}DeleteRequest{Id: state.Id.ValueString()})
}

// Helper conversions for list types
{{- range .Spec.Fields }}
{{- if eq .Type "list" }}
{{- if eq .ElemType "bool" }}
func tfListBools(ctx context.Context, l types.List) []bool {
	if l.IsNull() || l.IsUnknown() { return nil }
	var vals []types.Bool
	if diags := l.ElementsAs(ctx, &vals, false); diags.HasError() { return nil }
	out := make([]bool, 0, len(vals))
	for _, v := range vals { out = append(out, v.ValueBool()) }
	return out
}
func listBoolsToTF(ctx context.Context, xs []bool) types.List {
	vals := make([]attr.Value, 0, len(xs))
	for _, v := range xs { vals = append(vals, types.BoolValue(v)) }
	l, _ := types.ListValue(types.BoolType, vals)
	return l
}
{{- else if eq .ElemType "number" }}
func tfListFloat64s(ctx context.Context, l types.List) []float64 {
	if l.IsNull() || l.IsUnknown() { return nil }
	var vals []types.Float64
	if diags := l.ElementsAs(ctx, &vals, false); diags.HasError() { return nil }
	out := make([]float64, 0, len(vals))
	for _, v := range vals { out = append(out, v.ValueFloat64()) }
	return out
}
func listFloat64sToTF(ctx context.Context, xs []float64) types.List {
	vals := make([]attr.Value, 0, len(xs))
	for _, v := range xs { vals = append(vals, types.Float64Value(v)) }
	l, _ := types.ListValue(types.Float64Type, vals)
	return l
}
{{- else }}
func tfListStrings(ctx context.Context, l types.List) []string {
	if l.IsNull() || l.IsUnknown() { return nil }
	var vals []types.String
	if diags := l.ElementsAs(ctx, &vals, false); diags.HasError() { return nil }
	out := make([]string, 0, len(vals))
	for _, v := range vals { out = append(out, v.ValueString()) }
	return out
}
func listStringsToTF(ctx context.Context, xs []string) types.List {
	vals := make([]attr.Value, 0, len(xs))
	for _, v := range xs { vals = append(vals, types.StringValue(v)) }
	l, _ := types.ListValue(types.StringType, vals)
	return l
}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq .Role "datasource" }}
func New{{ .Spec.Name | Pascal }}DataSource() datasource.DataSource { return &{{ .Spec.Name | Pascal }}DataSource{} }

type {{ .Spec.Name | Pascal }}DataSource struct{ client *APIClient }

func (d *{{ .Spec.Name | Pascal }}DataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) { resp.TypeName = req.ProviderTypeName + "_{{ .Spec.Name }}" }
func (d *{{ .Spec.Name | Pascal }}DataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]dsschema.Attribute{}
	{{- range .Spec.Fields }}
	attrs["{{ .Name }}"] = {{ DSAttr . }}
	{{- end }}
	resp.Schema = dsschema.Schema{ Attributes: attrs }
}
func (d *{{ .Spec.Name | Pascal }}DataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil { return }
	c, ok := req.ProviderData.(*APIClient)
	if ok { d.client = c }
}
func (d *{{ .Spec.Name | Pascal }}DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	if d.client == nil { return }
	conn, err := grpc.Dial(d.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if d.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+d.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}DataSourceRead(ctx, &api.{{ .Spec.Name | Pascal }}DataSourceReadRequest{})
}
{{- end }}
{{- if eq .Role "ephemeral" }}
func New{{ .Spec.Name | Pascal }}Ephemeral() ephemeral.EphemeralResource { return &{{ .Spec.Name | Pascal }}Ephemeral{} }

type {{ .Spec.Name | Pascal }}Ephemeral struct{ client *APIClient }

func (e *{{ .Spec.Name | Pascal }}Ephemeral) Metadata(ctx context.Context, req ephemeral.MetadataRequest, resp *ephemeral.MetadataResponse) { resp.TypeName = req.ProviderTypeName + "_{{ .Spec.Name }}" }
func (e *{{ .Spec.Name | Pascal }}Ephemeral) Schema(ctx context.Context, req ephemeral.SchemaRequest, resp *ephemeral.SchemaResponse) {
	attrs := map[string]ephschema.Attribute{}
	{{- range .Spec.Fields }}
	attrs["{{ .Name }}"] = {{ EphAttr . }}
	{{- end }}
	resp.Schema = ephschema.Schema{ Attributes: attrs }
}
func (e *{{ .Spec.Name | Pascal }}Ephemeral) Configure(ctx context.Context, req ephemeral.ConfigureRequest, resp *ephemeral.ConfigureResponse) {
	if req.ProviderData == nil { return }
	c, ok := req.ProviderData.(*APIClient)
	if ok { e.client = c }
}
func (e *{{ .Spec.Name | Pascal }}Ephemeral) Open(ctx context.Context, req ephemeral.OpenRequest, resp *ephemeral.OpenResponse) {
	if e.client == nil { return }
	conn, err := grpc.Dial(e.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if e.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+e.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Open(ctx, &api.{{ .Spec.Name | Pascal }}OpenRequest{})
}
{{- end }}
`

// Note: templates for other generators live here. Adding minimal helpers for test server codegen inline in GenerateTestServer.
// small utilities used across files.
func funcMap() template.FuncMap {
	return template.FuncMap{
		"Pascal":           pascal,
		"HttpCreate":       httpCreatePath,
		"HttpRead":         httpReadPath,
		"HttpUpdate":       httpUpdatePath,
		"HttpDelete":       httpDeletePath,
		"HttpDsRead":       httpDsReadPath,
		"HttpOpen":         httpOpenPath,
		"ResourceAttr":     ResourceAttr,
		"DSAttr":           DSAttr,
		"EphAttr":          EphAttr,
		"ModelFieldType":   ModelFieldType,
		"NeedsTypesImport": NeedsTypesImport,
	}
}

// baseAttrFlags Attribute helpers.
func baseAttrFlags(f component.Field, isDataSource bool) (required, optional, computed bool) {
	// Modes override some behaviors
	switch f.Mode {
	case component.IDAttributeMode:
		computed = true
	case component.KeyAttributeMode:
		required = true
	}
	// Explicit flags
	if f.Optional {
		optional = true
		required = false
	}
	if f.Computed {
		computed = true
	}
	// Data sources default to computed unless user explicitly sets Optional
	if isDataSource && !optional && !computed {
		computed = true
	}
	// Score example (not optional) => required unless computed already set
	if !f.Optional && !required && !computed && !isDataSource && f.Mode != component.IDAttributeMode {
		required = true
	}
	return
}

func attrTypeCode(f component.Field, prefix string) string {
	switch f.Type {
	case "string":
		return prefix + "StringAttribute"
	case "bool":
		return prefix + "BoolAttribute"
	case "int64":
		return prefix + "Int64Attribute"
	case "number":
		return prefix + "Float64Attribute"
	case "list":
		return prefix + "ListAttribute"
	case "map":
		return prefix + "MapAttribute"
	default:
		return prefix + "StringAttribute"
	}
}

func elemTypeCode(elem string) string {
	// map list element type to types.*Type
	switch elem {
	case "string":
		return "types.StringType"
	case "bool":
		return "types.BoolType"
	case "int64":
		return "types.Int64Type"
	case "number":
		return "types.Float64Type"
	default:
		return "types.StringType"
	}
}

func buildAttr(f component.Field, prefix string, isDataSource bool) string {
	required, optional, computed := baseAttrFlags(f, isDataSource)
	typeName := attrTypeCode(f, prefix)
	var b strings.Builder
	b.WriteString(typeName)
	b.WriteString("{")
	flags := []string{}
	if required {
		flags = append(flags, "Required: true")
	}
	if optional {
		flags = append(flags, "Optional: true")
	}
	if computed {
		flags = append(flags, "Computed: true")
	}
	if f.Type == "list" || f.Type == "map" {
		flags = append(flags, fmt.Sprintf("ElementType: %s", elemTypeCode(f.ElemType)))
	}
	if f.Description != "" {
		flags = append(flags, fmt.Sprintf("MarkdownDescription: %q", f.Description))
	}
	b.WriteString(strings.Join(flags, ", "))
	b.WriteString("}")
	return b.String()
}

func ResourceAttr(f interface{}) string {
	cf, _ := f.(component.Field)
	return buildAttr(cf, "schema.", false)
}
func DSAttr(f interface{}) string {
	cf, _ := f.(component.Field)
	return buildAttr(cf, "dsschema.", true)
}
func EphAttr(f interface{}) string {
	cf, _ := f.(component.Field)
	// Ephemeral treat everything optional for flexibility
	cf.Optional = true
	return buildAttr(cf, "ephschema.", false)
}

// ModelFieldType Model field type mapping.
func ModelFieldType(f interface{}) string {
	cf, _ := f.(component.Field)
	switch cf.Type {
	case "string":
		return "types.String"
	case "bool":
		return "types.Bool"
	case "int64":
		return "types.Int64"
	case "number":
		return "types.Float64"
	case "list":
		return "types.List"
	case "map":
		return "types.Map"
	case "object":
		return "types.Object"
	default:
		return "types.String"
	}
}

// Determine if generated code needs to import terraform types package.
func NeedsTypesImport(spec component.Spec) bool {
	for _, f := range spec.Fields {
		if f.Type == "list" || f.Type == "map" {
			return true
		}
	}
	return false
}

func ResourceAttrLegacy(f interface{}) string { return "schema.StringAttribute{Required:true}" }

func init() {
	if strings.TrimSpace(modelTemplate) == "" || strings.TrimSpace(combinedProtoTemplateAuth) == "" {
		panic(errors.New("empty template"))
	}
}
