// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package generator

import (
	"errors"
	"strings"
	"text/template"
)

// Templates split out to keep files short

const modelTemplate = `// Code generated by componentgen; DO NOT EDIT.
package generated

import "github.com/hashicorp/terraform-plugin-framework/types"

type {{ .Name | Pascal }}Model struct {
{{ range .Fields }}	{{ .Name | Pascal }} types.String ` + "`tfsdk:\"{{ .Name }}\"`" + `
{{ end }}}
`

const combinedProtoTemplateAuth = `// Code generated by componentgen; DO NOT EDIT.
{{ if .Auth }}syntax = "proto3";
package {{ .Auth.Package }};
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
option go_package = "{{ .Auth.GoPackage }}";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: { title: "{{ .Auth.Title }}"; version: "{{ .Auth.Version }}"; }
  host: "{{ .Auth.Host }}";
  security_definitions: {
    security: { key: "oauth2", value: { type: TYPE_OAUTH2; flow: FLOW_APPLICATION; token_url: "{{ .Auth.TokenURL }}"; scopes: { scope: { key: "{{ .Auth.ReadScope }}"; value: "Read access"; }; scope: { key: "{{ .Auth.WriteScope }}"; value: "write access"; }; } } }
    security: { key: "bearerAuth", value: { type: TYPE_API_KEY; name: "Authorization"; in: IN_HEADER; } }
  }
  security: [ { security_requirement: { key: "oauth2"; value: { scope: ["{{ .Auth.ReadScope }}", "{{ .Auth.WriteScope }}"]; }; }, security_requirement: { key: "bearerAuth"; value: {}; } } ];
};
{{ else }}syntax = "proto3";
package {{ .Package }};
{{ if .HTTPImport }}import "google/api/annotations.proto";{{ end }}
option go_package = "{{ .GoPackage }}";
{{ end }}

// Messages
{{ range .Specs }}
// Component: {{ .Spec.Name }}
{{ range .Messages }}
message {{ .Name }} {
{{ range .Fields }}	{{ if .Repeated }}repeated {{ end }}{{ .Type }} {{ .Name }} = {{ .Tag }}; // {{ .Comment }}
{{ end }}
}
{{ end }}
{{ end }}

// Combined Service
service {{ .Service }} {
{{ range .Specs }}
{{ if .HasResource }}	rpc {{ .Spec.Name | Pascal }}Create({{ .Spec.Name | Pascal }}CreateRequest) returns ({{ .Spec.Name | Pascal }}CreateResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { post: "{{ HttpCreate .Spec.Name }}" body: "item" };
	}{{ else }};{{ end }}
	rpc {{ .Spec.Name | Pascal }}Read({{ .Spec.Name | Pascal }}ReadRequest) returns ({{ .Spec.Name | Pascal }}ReadResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { get: "{{ HttpRead .Spec.Name }}" };
	}{{ else }};{{ end }}
	rpc {{ .Spec.Name | Pascal }}Update({{ .Spec.Name | Pascal }}UpdateRequest) returns ({{ .Spec.Name | Pascal }}UpdateResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { put: "{{ HttpUpdate .Spec.Name }}" body: "item" };
	}{{ else }};{{ end }}
	rpc {{ .Spec.Name | Pascal }}Delete({{ .Spec.Name | Pascal }}DeleteRequest) returns ({{ .Spec.Name | Pascal }}DeleteResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { delete: "{{ HttpDelete .Spec.Name }}" };
	}{{ else }};{{ end }}
{{ end }}
{{ if .HasDataSource }}	rpc {{ .Spec.Name | Pascal }}DataSourceRead({{ .Spec.Name | Pascal }}DataSourceReadRequest) returns ({{ .Spec.Name | Pascal }}DataSourceReadResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { get: "{{ HttpDsRead .Spec.Name }}" };
	}{{ else }};{{ end }}
{{ end }}
{{ if .HasEphemeral }}	rpc {{ .Spec.Name | Pascal }}Open({{ .Spec.Name | Pascal }}OpenRequest) returns ({{ .Spec.Name | Pascal }}OpenResponse) {{ if and $.HTTP .Spec.Gateway }}{
		option (google.api.http) = { post: "{{ HttpOpen .Spec.Name }}" body: "item" };
	}{{ else }};{{ end }}
{{ end }}
{{ end }}
}
`

const goRoleTemplateV2 = `// Code generated by componentgen; DO NOT EDIT.
 package generated
 
 import (
 	"context"
 	{{- if eq .Role "resource" }}
 	// grpc client imports
 	"github.com/hashicorp/terraform-plugin-framework/resource"
 	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
 	"google.golang.org/grpc"
 	"google.golang.org/grpc/credentials/insecure"
 	"google.golang.org/grpc/metadata"
 	{{- end }}
 	{{- if eq .Role "datasource" }}
 	"github.com/hashicorp/terraform-plugin-framework/datasource"
 	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
 	"google.golang.org/grpc"
 	"google.golang.org/grpc/credentials/insecure"
 	"google.golang.org/grpc/metadata"
 	{{- end }}
 	{{- if eq .Role "ephemeral" }}
 	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
 	ephschema "github.com/hashicorp/terraform-plugin-framework/ephemeral/schema"
 	"google.golang.org/grpc"
 	"google.golang.org/grpc/credentials/insecure"
 	"google.golang.org/grpc/metadata"
 	{{- end }}
	api "github.com/gshireesh/terraform-provider-shireesh/internal/provider/generated/api"
 )

{{- if eq .Role "resource" }}
func New{{ .Spec.Name | Pascal }}Resource() resource.Resource { return &{{ .Spec.Name | Pascal }}Resource{} }

type {{ .Spec.Name | Pascal }}Resource struct{ client *APIClient }

func (r *{{ .Spec.Name | Pascal }}Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) { resp.TypeName = req.ProviderTypeName + "_{{ .Spec.Name }}" }
func (r *{{ .Spec.Name | Pascal }}Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{}
	{{- range .Spec.Fields }}
	attrs["{{ .Name }}"] = {{ ResourceAttr . }}
	{{- end }}
	resp.Schema = schema.Schema{ Attributes: attrs }
}
func (r *{{ .Spec.Name | Pascal }}Resource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil { return }
	c, ok := req.ProviderData.(*APIClient)
	if ok { r.client = c }
}
func (r *{{ .Spec.Name | Pascal }}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	if r.client == nil { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Create(ctx, &api.{{ .Spec.Name | Pascal }}CreateRequest{})
}
func (r *{{ .Spec.Name | Pascal }}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	if r.client == nil { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Read(ctx, &api.{{ .Spec.Name | Pascal }}ReadRequest{})
}
func (r *{{ .Spec.Name | Pascal }}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	if r.client == nil { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Update(ctx, &api.{{ .Spec.Name | Pascal }}UpdateRequest{})
}
func (r *{{ .Spec.Name | Pascal }}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	if r.client == nil { return }
	conn, err := grpc.Dial(r.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if r.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+r.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Delete(ctx, &api.{{ .Spec.Name | Pascal }}DeleteRequest{})
}
{{- end }}
{{- if eq .Role "datasource" }}
func New{{ .Spec.Name | Pascal }}DataSource() datasource.DataSource { return &{{ .Spec.Name | Pascal }}DataSource{} }

type {{ .Spec.Name | Pascal }}DataSource struct{ client *APIClient }

func (d *{{ .Spec.Name | Pascal }}DataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) { resp.TypeName = req.ProviderTypeName + "_{{ .Spec.Name }}" }
func (d *{{ .Spec.Name | Pascal }}DataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs := map[string]dsschema.Attribute{}
	{{- range .Spec.Fields }}
	attrs["{{ .Name }}"] = {{ DSAttr . }}
	{{- end }}
	resp.Schema = dsschema.Schema{ Attributes: attrs }
}
func (d *{{ .Spec.Name | Pascal }}DataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil { return }
	c, ok := req.ProviderData.(*APIClient)
	if ok { d.client = c }
}
func (d *{{ .Spec.Name | Pascal }}DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	if d.client == nil { return }
	conn, err := grpc.Dial(d.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if d.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+d.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}DataSourceRead(ctx, &{{ .Spec.Name | Pascal }}DataSourceReadRequest{})
}
{{- end }}
{{- if eq .Role "ephemeral" }}
func New{{ .Spec.Name | Pascal }}Ephemeral() ephemeral.EphemeralResource { return &{{ .Spec.Name | Pascal }}Ephemeral{} }

type {{ .Spec.Name | Pascal }}Ephemeral struct{ client *APIClient }

func (e *{{ .Spec.Name | Pascal }}Ephemeral) Metadata(ctx context.Context, req ephemeral.MetadataRequest, resp *ephemeral.MetadataResponse) { resp.TypeName = req.ProviderTypeName + "_{{ .Spec.Name }}" }
func (e *{{ .Spec.Name | Pascal }}Ephemeral) Schema(ctx context.Context, req ephemeral.SchemaRequest, resp *ephemeral.SchemaResponse) {
	attrs := map[string]ephschema.Attribute{}
	{{- range .Spec.Fields }}
	attrs["{{ .Name }}"] = {{ EphAttr . }}
	{{- end }}
	resp.Schema = ephschema.Schema{ Attributes: attrs }
}
func (e *{{ .Spec.Name | Pascal }}Ephemeral) Configure(ctx context.Context, req ephemeral.ConfigureRequest, resp *ephemeral.ConfigureResponse) {
	if req.ProviderData == nil { return }
	c, ok := req.ProviderData.(*APIClient)
	if ok { e.client = c }
}
func (e *{{ .Spec.Name | Pascal }}Ephemeral) Open(ctx context.Context, req ephemeral.OpenRequest, resp *ephemeral.OpenResponse) {
	if e.client == nil { return }
	conn, err := grpc.Dial(e.client.GRPCTarget(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil { return }
	defer conn.Close()
	cli := api.NewGrpcTerraformServiceClient(conn)
	if e.client.Bearer != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+e.client.Bearer) }
	_, _ = cli.{{ .Spec.Name | Pascal }}Open(ctx, &{{ .Spec.Name | Pascal }}OpenRequest{})
}
{{- end }}
`

// small utilities used across files
func funcMap() template.FuncMap {
	return template.FuncMap{"Pascal": pascal, "HttpCreate": httpCreatePath, "HttpRead": httpReadPath, "HttpUpdate": httpUpdatePath, "HttpDelete": httpDeletePath, "HttpDsRead": httpDsReadPath, "HttpOpen": httpOpenPath, "ResourceAttr": ResourceAttr, "DSAttr": DSAttr, "EphAttr": EphAttr}
}

func ResourceAttr(f interface{}) string { return "schema.StringAttribute{Required:true}" }
func DSAttr(f interface{}) string       { return "dsschema.StringAttribute{Required:true}" }
func EphAttr(f interface{}) string      { return "ephschema.StringAttribute{Required:true}" }

func init() {
	if strings.TrimSpace(modelTemplate) == "" || strings.TrimSpace(combinedProtoTemplateAuth) == "" {
		panic(errors.New("empty template"))
	}
}
