// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/gshireesh/terraform-provider-shireesh/internal/component"
)

// GenerateTestServer emits a simple in-memory gRPC server that implements the
// combined service for all resource components. It is intended for local and CI
// testing, not production. The server stores items in maps protected by a mutex
// and assigns random IDs on create.
func GenerateTestServer(specs []component.Spec, outDir string, apiImport string) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by componentgen; DO NOT EDIT.\n")
	b.WriteString("package fakeserver\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"net\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"net/http/httptest\"\n")
	b.WriteString("\t\"sync\"\n")
	b.WriteString("\t\"time\"\n")
	b.WriteString(fmt.Sprintf("\tapi \"%s\"\n", apiImport))
	b.WriteString("\t\"github.com/grpc-ecosystem/grpc-gateway/v2/runtime\"\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n")
	b.WriteString("\t\"google.golang.org/grpc/credentials/insecure\"\n")
	b.WriteString("\t\"google.golang.org/grpc/reflection\"\n")
	b.WriteString(")\n\n")

	// Type header
	b.WriteString("// InMemoryServer implements api.GrpcTerraformServiceServer with in-memory storage.\n")
	b.WriteString("type InMemoryServer struct {\n")
	b.WriteString("\tapi.UnimplementedGrpcTerraformServiceServer\n")
	b.WriteString("\tmu sync.RWMutex\n")
	// storage maps per resource
	for _, s := range specs {
		if !s.HasRole("resource") {
			continue
		}
		name := pascal(s.Name)
		b.WriteString(fmt.Sprintf("\t%s map[string]*api.%sReadOutput\n", strings.ToLower(name)+"Store", name))
	}
	b.WriteString("}\n\n")

	// constructor
	b.WriteString("func NewInMemoryServer() *InMemoryServer {\n")
	b.WriteString("\ts := &InMemoryServer{}\n")
	for _, s := range specs {
		if !s.HasRole("resource") {
			continue
		}
		name := pascal(s.Name)
		b.WriteString(fmt.Sprintf("\ts.%s = make(map[string]*api.%sReadOutput)\n", strings.ToLower(name)+"Store", name))
	}
	b.WriteString("\treturn s\n}\n\n")

	// Add CRUD methods per resource
	for _, s := range specs {
		if !s.HasRole("resource") {
			continue
		}
		pname := pascal(s.Name)
		store := strings.ToLower(pname) + "Store"
		// Create
		b.WriteString(fmt.Sprintf("func (s *InMemoryServer) %sCreate(ctx context.Context, req *api.%sCreateRequest) (*api.%sCreateResponse, error) {\n", pname, pname, pname))
		b.WriteString("\ts.mu.Lock()\n\tdefer s.mu.Unlock()\n")
		b.WriteString("\tid := fmt.Sprintf(\"id-%d\", time.Now().UnixNano())\n")
		b.WriteString(fmt.Sprintf("\tout := &api.%sCreateOutput{Id: id}\n", pname))
		// assign fields from input if present
		b.WriteString("\tif req != nil && req.Item != nil {\n")
		for _, f := range s.Fields {
			if f.Name == "id" {
				continue
			}
			fn := pascal(f.Name)
			b.WriteString(fmt.Sprintf("\t\tout.%s = req.Item.%s\n", fn, fn))
		}
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tif s.%s == nil { s.%s = make(map[string]*api.%sReadOutput) }\n", store, store, pname))
		b.WriteString(fmt.Sprintf("\ts.%s[id] = &api.%sReadOutput{\n\t\tId: out.Id,\n", store, pname))
		for _, f := range s.Fields {
			if f.Name == "id" {
				continue
			}
			b.WriteString(fmt.Sprintf("\t\t%s: out.%s,\n", pascal(f.Name), pascal(f.Name)))
		}
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\treturn &api.%sCreateResponse{Item: out}, nil\n}\n\n", pname))
		// Read
		b.WriteString(fmt.Sprintf("func (s *InMemoryServer) %sRead(ctx context.Context, req *api.%sReadRequest) (*api.%sReadResponse, error) {\n", pname, pname, pname))
		b.WriteString("\ts.mu.RLock()\n\tdefer s.mu.RUnlock()\n")
		b.WriteString("\tif req == nil || req.Id == \"\" { return &api." + pname + "ReadResponse{}, nil }\n")
		b.WriteString(fmt.Sprintf("\tif it, ok := s.%s[req.Id]; ok {\n", store))
		b.WriteString(fmt.Sprintf("\t\treturn &api.%sReadResponse{Item: &api.%sReadOutput{\n\t\t\tId: it.Id,\n", pname, pname))
		for _, f := range s.Fields {
			if f.Name == "id" {
				continue
			}
			b.WriteString(fmt.Sprintf("\t\t\t%s: it.%s,\n", pascal(f.Name), pascal(f.Name)))
		}
		b.WriteString("\t\t}}, nil\n\t}\n")
		b.WriteString(fmt.Sprintf("\treturn &api.%sReadResponse{}, nil\n}\n\n", pname))
		// Update
		b.WriteString(fmt.Sprintf("func (s *InMemoryServer) %sUpdate(ctx context.Context, req *api.%sUpdateRequest) (*api.%sUpdateResponse, error) {\n", pname, pname, pname))
		b.WriteString("\ts.mu.Lock()\n\tdefer s.mu.Unlock()\n")
		b.WriteString(fmt.Sprintf("\tit, ok := s.%s[req.GetId()]\n", store))
		b.WriteString("\tif !ok { return &api." + pname + "UpdateResponse{}, nil }\n")
		b.WriteString("\tif req != nil && req.Item != nil {\n")
		for _, f := range s.Fields {
			if f.Name == "id" {
				continue
			}
			b.WriteString(fmt.Sprintf("\t\tit.%s = req.Item.%s\n", pascal(f.Name), pascal(f.Name)))
		}
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tout := &api.%sUpdateOutput{\n\t\tId: it.Id,\n", pname))
		for _, f := range s.Fields {
			if f.Name == "id" {
				continue
			}
			b.WriteString(fmt.Sprintf("\t\t%s: it.%s,\n", pascal(f.Name), pascal(f.Name)))
		}
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\treturn &api.%sUpdateResponse{Item: out}, nil\n}\n\n", pname))
		// Delete
		b.WriteString(fmt.Sprintf("func (s *InMemoryServer) %sDelete(ctx context.Context, req *api.%sDeleteRequest) (*api.%sDeleteResponse, error) {\n", pname, pname, pname))
		b.WriteString("\ts.mu.Lock()\n\tdefer s.mu.Unlock()\n")
		b.WriteString(fmt.Sprintf("\tif s.%s != nil { delete(s.%s, req.GetId()) }\n", store, store))
		b.WriteString(fmt.Sprintf("\treturn &api.%sDeleteResponse{Success: true}, nil\n}\n\n", pname))
	}

	// Start helper: launches gRPC and HTTP gateway on the same dynamic listener using httptest.Server.
	b.WriteString("// Start launches a gRPC server and HTTP JSON gateway on a local ephemeral address.\n")
	b.WriteString("// Returns the *httptest.Server (for HTTP base URL) and a grpc Dial target (host:port).\n")
	b.WriteString("func (s *InMemoryServer) Start(ctx context.Context) (*httptest.Server, string, error) {\n")
	b.WriteString("\t// gRPC on random port\n")
	b.WriteString("\tlis, err := net.Listen(\"tcp\", \"127.0.0.1:0\")\n")
	b.WriteString("\tif err != nil { return nil, \"\", err }\n")
	b.WriteString("\tgrpcSrv := grpc.NewServer(grpc.Creds(insecure.NewCredentials()))\n")
	b.WriteString("\tapi.RegisterGrpcTerraformServiceServer(grpcSrv, s)\n")
	b.WriteString("\treflection.Register(grpcSrv)\n")
	b.WriteString("\tgo grpcSrv.Serve(lis)\n")
	b.WriteString("\tgrpcTarget := lis.Addr().String()\n")
	b.WriteString("\t// HTTP JSON gateway mux that proxies to the same server\n")
	b.WriteString("\tglue := runtime.NewServeMux()\n")
	b.WriteString("\tcc, err := grpc.DialContext(ctx, grpcTarget, grpc.WithTransportCredentials(insecure.NewCredentials()))\n")
	b.WriteString("\tif err != nil { return nil, \"\", err }\n")
	b.WriteString("\tif err := api.RegisterGrpcTerraformServiceHandlerClient(ctx, glue, api.NewGrpcTerraformServiceClient(cc)); err != nil { return nil, \"\", err }\n")
	b.WriteString("\th := http.NewServeMux()\n")
	b.WriteString("\th.Handle(\"/\", glue)\n")
	b.WriteString("\tserver := httptest.NewServer(h)\n")
	b.WriteString("\treturn server, grpcTarget, nil\n")
	b.WriteString("}\n")

	outFile := filepath.Join(outDir, "test_server.gen.go")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create fakeserver dir: %w", err)
	}
	if err := os.WriteFile(outFile, b.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write test server: %w", err)
	}
	return nil
}
